title: 'Shri Ganesha Puja: Keep Your Maryadas'
date: '1984-01-15'
location: Mumbai (India)
amruta_url: https://www.amruta.org/1984/01/15/shri-ganesha-puja-mumbai-1984/
language: en
videos:
- slug: Shri-Ganesha-Puja-Talk
  title: Shri Ganesha Puja Talk
  video_ref: r1ElcPFV8WWxFAS05SWk4aU11SXVFC
