title: 'Shri Ganesha Puja: Ritualism is not innocence'
date: '1993-09-19'
location: Campus, Cabella Ligure (Italy)
amruta_url: https://www.amruta.org/1993/09/19/ganesha-puja-cabella-1993/
language: en
videos:
- slug: Ganesha-Puja
  title: Ganesha Puja
  vimeo_url: https://vimeo.com/333507352/d3be3e6222
- slug: Ganesha-Puja-Talk
  title: Ganesha Puja Talk
  vimeo_url: https://vimeo.com/333503693/6e326bc213
