title: 'Sahasrara Puja: Jump Into the Ocean of Joy'
date: '1989-05-06'
location: Sorrento (Italy)
amruta_url: https://www.amruta.org/1989/05/06/sahasrara-puja-1989/
language: en
videos:
- slug: Sahasrara-Puja
  title: Sahasrara Puja
  vimeo_url: https://vimeo.com/733952351/3b38f05734
- slug: Sahasrara-Puja-Talk
  title: Sahasrara Puja Talk
  vimeo_url: https://vimeo.com/774270833/b5a391fe8f
