title: From Heart to Sahasrara
date: '1982-07-11'
location: Derby
amruta_url: https://www.amruta.org/1982/07/11/from-heart-to-sahastrar-derby-1982/
language: uk
videos:
- slug: From-Heart-to-Sahasrara
  title: From Heart to Sahasrara
  vimeo_url: https://player.vimeo.com/video/88526096?h=042ac11698&badge=0&autopause=0&player_id=0&app_id=58479&texttrack=en&dnt=1
