title: 'Talk to Sahaja Yogis: Religion is Within'
date: '1992-02-25'
location: Cranford Motel, Christchurch (New Zealand)
amruta_url: https://www.amruta.org/1992/02/25/talk-to-yogis-in-christchurch-1992/
language: uk
videos:
- slug: Talk-to-Sahaja-Yogis-Religion-is-Within
  title: 'Talk to Sahaja Yogis: Religion is Within'
  vimeo_url: https://vimeo.com/133567566/7f433fb08f
