title: 'Talk to Sahaja Yogis: Religion is Within'
date: '1992-02-25'
location: ''
amruta_url: https://www.amruta.org/1992/02/25/talk-to-yogis-in-christchurch-1992/
language: uk
videos:
- slug: Talk-to-Sahaja-Yogis-Religion-is-Within
  title: 'Talk to Sahaja Yogis: Religion is Within'
  vimeo_url: https://player.vimeo.com/video/133567566?h=7f433fb08f&badge=0&autopause=0&player_id=0&app_id=58479&texttrack=en&dnt=1
