title: 'Birthday Puja: A Great Day in History'
date: '1981-03-21'
location: Sydney (Australia)
amruta_url: https://www.amruta.org/1981/03/21/birthday-puja-1981-sydney/
language: en
videos:
- slug: Birthday-Puja
  title: Birthday Puja
  vimeo_url: https://vimeo.com/285206215/da33251ae2
- slug: Birthday-Puja-Talk
  title: Birthday Puja Talk
  vimeo_url: https://vimeo.com/285209090/3a25cabd68
