title: "Guru Puja: Awakening the Principle of Guru"
date: "1983-07-24"
location: "Lodge Hill, Sussex, UK"
amruta_url: "https://www.amruta.org/1983/07/24/guru-puja-awakening-the-principle-of-guru/"
vimeo_url: ""
language: uk
