title: 'Shri Krishna Puja: Ananya Bhakti'
date: '2001-07-29'
location: Nirmal Nagari, Canajoharie (United States)
amruta_url: https://www.amruta.org/2001/07/29/shri-krishna-puja-new-york-2001/
language: uk
videos:
- slug: Krishna-Puja
  title: Krishna Puja
  vimeo_url: https://vimeo.com/88444291/558a575bd0
- slug: Krishna-Puja-Talk
  title: Krishna Puja Talk
  vimeo_url: https://vimeo.com/88512223/b46dbb4340
