title: 'Adi Shakti Puja: The steadiness of the mind is very important for the marriages'
date: '1988-12-11'
location: Residence of Madhukar Dhumal, Rahuri (India)
amruta_url: https://www.amruta.org/1988/12/11/shri-adi-shakti-puja-rahuri-1988/
language: en
videos:
- slug: Adi-Shakti-Puja-Cam-2
  title: Adi Shakti Puja Cam 2
  vimeo_url: https://vimeo.com/483626043/6331b6653e
- slug: Adi-Shakti-Puja-Cam-1
  title: Adi Shakti Puja Cam 1
  vimeo_url: https://vimeo.com/483624293/ecb99b3c7a
- slug: Adi-Shakti-Puja-Talk-Detachment
  title: 'Adi Shakti Puja Talk: Detachment'
  vimeo_url: https://vimeo.com/483617157/7407cd9b57
other_languages:
- mr
