title: 'Shri Ganesha Puja: Ritualism is not innocence'
date: '1993-09-19'
location: Cabella
amruta_url: https://www.amruta.org/1993/09/19/ganesha-puja-cabella-1993/
vimeo_url: https://player.vimeo.com/video/333507352?h=d3be3e6222&badge=0&autopause=0&player_id=0&app_id=58479&texttrack=en&dnt=1
language: uk
