title: 'Birthday Puja: Be Sweet, Loving and Peaceful'
date: '1984-03-22'
location: Juhu, Mumbai (India)
amruta_url: https://www.amruta.org/1984/03/22/birthday-puja-1984/
language: en
videos:
- slug: Birthday-Puja-Talk-Be-Sweet
  title: 'Birthday Puja Talk: Be Sweet'
  vimeo_url: https://vimeo.com/393388291/2a9b09d251
other_languages:
- mr
