title: 'Adi Shakti Puja: The compassion has to become active'
date: '1996-06-09'
location: Campus, Cabella Ligure (Italy)
amruta_url: https://www.amruta.org/1996/06/09/shri-adi-shakti-puja-1996/
language: en
videos:
- slug: Adi-Shakti-Puja-Cabella-Italy-DP-RAW
  title: Adi Shakti Puja Cabella Italy DP-RAW
  vimeo_url: https://vimeo.com/821261193/4caeb1a699
- slug: Adi-Shakti-Puja-Talk-Cabella-Italy-DP-RAW
  title: Adi Shakti Puja Talk Cabella Italy DP-RAW
  vimeo_url: https://vimeo.com/821261147/02ac3766fa
