title: 'Easter Puja: You Cannot Resurrect Yourself Without Controlling Agnya'
date: '2001-04-22'
location: Ataköy Marina Hotel, Istanbul (Turkey)
amruta_url: https://www.amruta.org/2001/04/22/easter-puja-2001/
language: en
videos:
- slug: Easter-Puja-Istanbul-Turkey-DP-RAW
  title: Easter Puja Istanbul Turkey DP-RAW
  vimeo_url: https://vimeo.com/1082552265/05734685aa
- slug: Easter-Puja-Talk-Istanbul-Turkey-DP-RAW
  title: Easter Puja Talk Istanbul Turkey DP-RAW
  vimeo_url: https://vimeo.com/1082552497/a263d6d9a7
