title: 'Mahashivaratri Puja: The importance of Shiva'
date: '1979-02-25'
location: Pune
amruta_url: https://www.amruta.org/1979/02/25/puja-in-pune-marathi-1979/
language: uk
videos:
- slug: Mahashivaratri-Puja
  title: Mahashivaratri Puja
  vimeo_url: https://player.vimeo.com/video/916194756?h=a4fda18b19&badge=0&autopause=0&player_id=0&app_id=58479&texttrack=en&dnt=1
