title: 'Sahasrara Puja: How it was decided'
date: '1988-05-08'
location: Fregene (Italy)
amruta_url: https://www.amruta.org/1988/05/08/sahasrara-puja-1988/
language: en
videos:
- slug: Sahasrara-Puja
  title: Sahasrara Puja
  vimeo_url: https://vimeo.com/88490248/e956098e13
- slug: Sahasrara-Puja-Talk
  title: Sahasrara Puja Talk
  vimeo_url: https://vimeo.com/88509806/2453ea7524
