title: 'Shri Vishnumaya Puja: She has created a big maya'
date: '1987-08-09'
location: YWCA Camp, Pawling (United States)
amruta_url: https://www.amruta.org/1987/08/09/shri-vishnumaya-puja-new-york-1987/
language: en
videos:
- slug: Vishnumaya-Puja
  title: Vishnumaya Puja
  vimeo_url: https://vimeo.com/88489964/403b6b82ef
- slug: Vishnumaya-Puja-Talk
  title: Vishnumaya Puja Talk
  vimeo_url: https://vimeo.com/88510508/556e9c0276
