title: 'Birthday Puja Talk: Guarding Against Slothfulness'
date: '1980-03-23'
location: 4A Castletown Rd, London (England)
amruta_url: https://www.amruta.org/1980/03/23/birthday-puja-1980/
language: uk
videos:
- slug: Birthday-Puja
  title: Birthday Puja
  vimeo_url: https://vimeo.com/1053728113/0eb30eb11e
- slug: Birthday-Puja
  title: Birthday Puja
  vimeo_url: https://vimeo.com/925431865/6ac0d66cab
